### ISSUE TITLE
Dropship Crash

### ISSUE THREAD

**Issue by IJARika** [R2Northstar/NorthstarLauncher#1]
Dedicated server seemingly crashing on dropship spawn.

**Comment by L1ghtman2k** [comment]
On server side, this might be related to this error: 
![image](https://user-images.githubusercontent.com/35672535/147346212-50eb068a-f8d8-4183-a595-b52e5263fb42.png)

**Comment by IJARika** [comment]
Yeah seemed like it.

**Comment by BobTheBob9** [comment]
this is patched on latest commit to NorthstarMods, should be in next release
