### ISSUE TITLE
Make clang-format behave more sensible

### ISSUE THREAD

**Issue by GeckoEidechse** [R2Northstar/NorthstarLauncher#119]
We had a bunch of contributors complaining by now that clang-format messed up their technically well-formatted code.

We should make sure that clang-format enforces code style while also not creating weird formatting situations on supposedly well formatted code.

Useful tool: https://zed0.co.uk/clang-format-configurator/

**Comment by KittenPopo** [comment]
To fix a lot of issues, add:
`SpaceAfterLogicalNot: false
SpaceAfterTemplateKeyword: true
SpaceBeforeAssignmentOperators: true
SpaceBeforeCpp11BracedList: true
SpaceBeforeCtorInitializerColon: true
SpaceBeforeInheritanceColon: true
SpaceBeforeParens: ControlStatements
SpaceBeforeRangeBasedForLoopColon: true
NamespaceIndentation: All
AlignTrailingComments: false
AllowAllConstructorInitializersOnNextLine: false
AllowAllParametersOfDeclarationOnNextLine: true
AllowShortFunctionsOnASingleLine: Empty
AlwaysBreakAfterDefinitionReturnType: None
AlwaysBreakAfterReturnType: None
AlwaysBreakTemplateDeclarations: No
BinPackArguments: false
BinPackParameters: false
BreakBeforeTernaryOperators: false
BreakStringLiterals: false
ExperimentalAutoDetectBinPacking: false
IndentCaseLabels: false
ObjCBinPackProtocolList: Auto
SpaceAfterCStyleCast: false
SpaceInEmptyParentheses: false
Standard: Cpp11`

Original clang-format:
`NSMem::BytePatch(
		ba + 0x18ED8D, {
								    0xC3 // jmp => ret
								 });`

After adding these changes:
`NSMem::BytePatch(
		ba + 0x18ED8D,
		{
			0xC3 // jmp => ret
		});`

**Comment by KittenPopo** [comment]
I recommend adding:
```
SpaceAfterLogicalNot: false
SpaceAfterTemplateKeyword: true
SpaceBeforeAssignmentOperators: true
SpaceBeforeCpp11BracedList: true
SpaceBeforeCtorInitializerColon: true
SpaceBeforeInheritanceColon: true
SpaceBeforeParens: ControlStatements
SpaceBeforeRangeBasedForLoopColon: true
NamespaceIndentation: All
AlignTrailingComments: false
AllowAllConstructorInitializersOnNextLine: false
AllowAllParametersOfDeclarationOnNextLine: true
AllowShortFunctionsOnASingleLine: Empty
AlwaysBreakAfterDefinitionReturnType: None
AlwaysBreakAfterReturnType: None
AlwaysBreakTemplateDeclarations: No
BinPackArguments: false
BinPackParameters: false
ExperimentalAutoDetectBinPacking: false
IndentCaseLabels: false
ObjCBinPackProtocolList: Auto
SpaceAfterCStyleCast: false
SpaceInEmptyParentheses: false
Standard: Cpp11
```
This fixes basically all the issues I have with clang-format, and specifies some more strict formatting rules (I based this on what is already used in the code).

**Comment by GeckoEidechse** [comment]
^--- @abarichello might wanna check that out ;)

**Comment by cpdt** [comment]
These lines from @KittenPopo's config should be enough to fix those pathological "to the moon" cases:

```
BinPackArguments: false
BinPackParameters: false
ExperimentalAutoDetectBinPacking: false
```

clang-format 14 also supports `AlignAfterOpenBracket: BlockIndent`, which turns this:

```cpp
NSMem::BytePatch(
    ba + 0x18ED8D,
    {
        0xC3 // jmp => ret
    });
```

into this, which is maybe a bit cleaner:

```cpp
NSMem::BytePatch(
    ba + 0x18ED8D,
    {
        0xC3 // jmp => ret
    }
);
```

**Comment by KittenPopo** [comment]
Sweet, we should upgrade to 14 lol

**Comment by GeckoEidechse** [comment]
clang-format 14 only released like 3 weeks ago, so [the action we use](https://github.com/DoozyX/clang-format-lint-action) doesn't support it yet :c

I [opened an issue with them for now](https://github.com/DoozyX/clang-format-lint-action/issues/39) to see if/when support will be added.

**Comment by GeckoEidechse** [comment]
Before messing with clang-format we should probably make sure that it accepts current code. Hence #143 to format code to current version of clang-format.
