### ISSUE TITLE
User-agent version incorrect when launching with alternative mechanisms

### ISSUE THREAD

**Issue by pg9182** [R2Northstar/NorthstarLauncher#129]
As discovered during testing, we'll need to build the version number into the DLL so we can still extract it even when launched via vanilla titanfall 2 and the launcher proxy or wsock32 stub (i.e., steam).

#113

**Comment by pg9182** [comment]
This issue needs to be fixed ASAP for v1.6.1 (which also needs to be released ASAP).

**Comment by pg9182** [comment]
cc @GeckoEidechse @emma-miler

**Comment by pg9182** [comment]
Required changes to fix this:

- We get the DLL's module handle in dllmain, so we need to store the handle or calculate the version at that time.
- We need to add a manifest resource to the DLL.

**Comment by GeckoEidechse** [comment]
Reproduced when running `v1.6.0` with `-northstar`, user agent is incorrect:

![grafik](https://user-images.githubusercontent.com/40122905/160653491-eaa77a7a-7df8-46ba-9c26-41e8e556e0c5.png)
