### ISSUE TITLE
Silent DiscordRPC crashes without Discord

### ISSUE THREAD

**Issue by pg9182** [R2Northstar/NorthstarLauncher#130]
Needs more investigation.

https://discord.com/channels/920776187884732556/958391842536308756

**Comment by pg9182** [comment]
Possibly related: https://github.com/discord/gamesdk-and-dispatch/issues/37.

**Comment by emma-miler** [comment]
Seems to be related to `discord_game_sdk.dll` not finding a running/installed version of discord. Honestly not sure how to catch this error, or what even causes it, since i already pass `DiscordCreateFlags_NoRequireDiscord` to the core creation function

**Comment by emma-miler** [comment]
@GeckoEidechse request to close

**Comment by lundmark** [comment]
Hi, this did not solve the crash. It still happens. The crash I'm referring to is this one: https://github.com/discord/gamesdk-and-dispatch/issues/37
