### ISSUE TITLE
Detect Wine/Proton version to warn user if running under unsupported versions

### ISSUE THREAD

**Issue by GeckoEidechse** [R2Northstar/NorthstarLauncher#138]
To help with users running Northstar under unsupported Wine/Proton versions it was suggested to check the version the game is running under to display some information if the version is an unsupported one.

Ultimately we need to work on better Wine/Proton support but this should help as a stop-gap solution.

**Comment by GeckoEidechse** [comment]
Detecting Wine version as suggested in [this Stackoverflow thread](https://stackoverflow.com/questions/7372388/determine-whether-a-program-is-running-under-wine-at-runtime/42333249#42333249)

Compiling the following code on Windows

```C
#include <windows.h>
#include <stdio.h>
int main(void)
{
    static const char *(CDECL *pwine_get_version)(void);
    HMODULE hntdll = GetModuleHandle("ntdll.dll");
    if(!hntdll)
    {
        puts("Not running on NT.");
        return 1;
    }

    pwine_get_version = (void *)GetProcAddress(hntdll, "wine_get_version");
    if(pwine_get_version)
    {
        printf("Running on Wine... %s\n",pwine_get_version());
    }
    else
    {
        puts("did not detect Wine.");
    }
    int my_int;
    scanf("%d", &my_int);

    return 0;
}
```

and then running executable on SteamOS 3.0 with the same version for Proton as we use for Northstar, we get:

```
Running on Wine... 7.3
```

i.e. detected Wine/Proton version is `7.3`.
This is an issue as that means we cannot reliably detect if it's the actual right Proton flavour (i.e. Proton-GE vs Proton vs Wine), just if it's the right version of that flavour.

**Comment by Jan200101** [comment]
There are wine internal functions that can be called that would let us identify where the Proton prefix is and from there access the relevant `version` file, so there would be no problem in figuring out what Proton version we are running.

Question is, where do we log this information? How do we inform the user about this?

And while we are at it, are there any other places that would benefit from wine detection? (There is at least 1 function in engine.dll that tries to identify the Windows version and the `status` command has a hardcoded `"Windows"` string)

**Comment by Jan200101** [comment]
Correct, it makes no sense to check.

Proton 8 works out of the box
Proton 7 works with a DLL override and IGO64.dll disabled
All recent releases of GE-Proton work out of the box
NorthstarProton works out of the box

Only issue that still exists is Nvidia's 535 series of drivers running out of memory during setup causing prefix creation failure, but that is out of our control.

**Comment by GeckoEidechse** [comment]
Closing as _NOT PLANNED_
