### ISSUE TITLE
Log failure to create auth server

### ISSUE THREAD

**Issue by Alainx277** [R2Northstar/NorthstarLauncher#142]
The authentication HTTP servers is started by calling `listen` [here](https://github.com/R2Northstar/NorthstarLauncher/blob/8d242da7981204ea61b4678741a7cfe73d337442/NorthstarDedicatedTest/serverauthentication.cpp#L133). It returns a bool to indicate failure or success, which is ignored.

Running two servers on the same machine without changing the auth server port will silently error, as only the first server can listen on the port.

It would be way easier to troubleshoot if it would log on failure.

**Comment by ASpoonPlaysGames** [comment]
Closing as stale, I don't think we even use an auth server anymore
