### ISSUE TITLE
default persistence for insecure auth should be more dynamic

### ISSUE THREAD

**Issue by BobTheBob9** [R2Northstar/NorthstarLauncher#149]
there's been some work on mod persistence recently, mod persistence in general is kind of an issue for how we currently handle insecure auth, which is just through reading a file from disk directly into a buffer
this only works really for vanilla persistence, so we need to change how we do this to better support mod persistence
potentially we could populate this in script? rather than reading from a buffer we could just null out all persistence, then call InitPersistentData for client on connect in script, which could work i think

**Comment by ASpoonPlaysGames** [comment]
This was done a while back now
