### ISSUE TITLE
Game gets stuck on the menu

### ISSUE THREAD

**Issue by dtoll2002** [R2Northstar/NorthstarLauncher#15]
I was able to play when I first installed it but now it loads the screen that you would normally see the animation and Menu. I get the animation but no menu. There is an error on the console:

[info] Enabling hook OnCommandSubmittedHook
[info] Building custom scripts.rson
[info] changing mod search path from E:\Titanfall 2\Titanfall2\R2Northstar\mods\Northstar.Custom\mod to R2Northstar/mods\Northstar.Client
[info] changing mod search path from E:\Titanfall 2\Titanfall2\R2Northstar\mods\Northstar.Client\mod to R2Northstar/mods\Northstar.Custom
[info] changing mod search path from E:\Titanfall 2\Titanfall2\R2Northstar\mods\Northstar.Custom\mod to R2Northstar/mods\Northstar.Client
[info] changing mod search path from E:\Titanfall 2\Titanfall2\R2Northstar\mods\Northstar.Client\mod to R2Northstar/mods\Northstar.Custom
[info] changing mod search path from E:\Titanfall 2\Titanfall2\R2Northstar\mods\Northstar.Custom\mod to R2Northstar/mods\Northstar.Client
[error] CLIENT SCRIPT COMPILE ERROR Undefined variable "IsNorthstarServer"
[error] ui/openinvites.nut line [205] column [50]
[info] DestroyVM UI 0x626e700
[info] Building KeyValues for file playlists_v2.txt
[info] MountVPK vpk/client_mp_common.bsp
[info] MountVPK R2Northstar/mods\Northstar.Custom\vpk\client_mp_northstar_common.bsp
[info] 0x45cee80
[info] MountVPK vpk/client_mp_common.bsp
[info] MountVPK R2Northstar/mods\Northstar.Custom\vpk\client_mp_northstar_common.bsp
[info] 0x45cee80

**Comment by BobTheBob9** [comment]
Delete the enabledmods.json file at gamedir/R2Northstar/ and verify your game files, if neither of those work uninstall Northstar

**Comment by dtoll2002** [comment]
That worked! Thanks man!!
