### ISSUE TITLE
Print loaded mods into logs

### ISSUE THREAD

**Issue by GeckoEidechse** [R2Northstar/NorthstarLauncher#154]
Should help with debugging, in particular ensuring that no extra mod was loaded while looking for a bug.

**Comment by H0L0theBard** [comment]
Pretty sure this already exists in modmanager.cpp 
https://github.com/R2Northstar/NorthstarLauncher/blob/286cea5f6280e568f5cb4c953d93993c98625ce4/NorthstarDedicatedTest/modmanager.cpp#L295-L306
