### ISSUE TITLE
PlayerToken and UID is shown in the console

### ISSUE THREAD

**Issue by iTzNao** [R2Northstar/NorthstarLauncher#177]
PlayerToken and UID is shown in the console, I got hacked because of it, it should not display it in the console.

**Comment by r3muxd** [comment]
a

**Comment by ASpoonPlaysGames** [comment]
UIDs are public information, can be got from the origin API from a username, as for player tokens, I was not aware of us logging origin tokens? Can you provide a screenshot (censor the token though) or something?

**Comment by GeckoEidechse** [comment]
As @ASpoonPlaysGames says, UIDs have basically the same sensitivity as usernames with the only difference being that they cannot be changed. Anyone with an Origin account can lookup someone else's UID based on username and vice versa.

On the note of PlayerToken, I couldn't find anything in my logs when checking rn. But even then, tokens should be one-time use, meaning they are invalidated the moment they get sent once.

(screenshots are of course still welcome if you have any to make sure we're talking about the same thing ^^)

**Comment by iTzNao** [comment]
> UIDs are public information, can be got from the origin API from a username, as for player tokens, I was not aware of us logging origin tokens? Can you provide a screenshot (censor the token though) or something?

We don't log them, it is shown in the console when northstar starts up, meaning if you are sharing your screen or have someone next to you, your account token is compromised

**Comment by GabanKillasta** [comment]
They are arguing it shouldn't be shown in console, because they were streaming and showed the console for a couple seconds and someone got their token

**Comment by KittenPopo** [comment]
> But even then, tokens should be one-time use, meaning they are invalidated the moment they get sent once.

Yeah, totally... They definitely aren't permanent... 💀

**Comment by iTzNao** [comment]
> > But even then, tokens should be one-time use, meaning they are invalidated the moment they get sent once.
> 
> Yeah, totally... 💀
> 
> > it is shown in the console when northstar starts up, meaning if you are sharing your screen or have someone next to you, your account token is compromised
> 
> This is literally just wrong, wot? Console never prints token. It will show UID though:
> 
> ![image](https://user-images.githubusercontent.com/28826980/170413399-1f03e302-4de4-48df-8087-ab86891ac842.png)
> 
> Origin account UIDs are neither sensitive information nor useful for anything other than knowing someone's account. Usernames are the same way.
> 
> If a streamer doesn't want anyone to know their username, just don't show console? (also dont play on any servers or launch any multiplayer stuff)

You are wrong, it does print out the origin token, this is how they changed my pfp and signed into titanfall as me as TTV-iTz_Nao(1) while in karma's server.

![Screenshot 2022-05-26 121556](https://user-images.githubusercontent.com/63752443/170477634-171d6033-4f13-4d01-ae55-142514827ff3.png)

**Comment by ASpoonPlaysGames** [comment]
thats... rather annoying

**Comment by F1F7Y** [comment]
( UID is basically public information, the token part is problematic though )

**Comment by ASpoonPlaysGames** [comment]
I cant rly seem to get the game to be printing that the console at all, I assume it's printing it roughly here for you
![image](https://user-images.githubusercontent.com/66967891/170480071-b14de80a-e477-44f6-b904-9ffb92533021.png)

**Comment by iTzNao** [comment]
```cpp
void MasterServerManager::AuthenticateOriginWithMasterServer(char* uid, char* originToken)
{
	if (m_bOriginAuthWithMasterServerInProgress)
		return;

	// do this here so it's instantly set
	m_bOriginAuthWithMasterServerInProgress = true;
	std::string uidStr(uid);
	std::string tokenStr(originToken);

	std::thread requestThread(
		[this, uidStr, tokenStr]()
		{
			spdlog::info("Trying to authenticate with northstar masterserver for user {}", uidStr);

			CURL* curl = curl_easy_init();
			SetCommonHttpClientOptions(curl);
			std::string readBuffer;
			curl_easy_setopt(
				curl,
				CURLOPT_WRITEFUNCTION,
				CURLOPT_URL,
				fmt::format("{}/client/origin_auth?id={}&token={}", Cvar_ns_masterserver_hostname->GetString(), uidStr, tokenStr).c_str());
			curl_easy_setopt(curl, CURLOPT_CUSTOMREQUEST, "GET");
			curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, CurlWriteToStringBufferCallback);
			curl_easy_setopt(curl, CURLOPT_WRITEDATA, &readBuffer);

			CURLcode result = curl_easy_perform(curl);

			if (result == CURLcode::CURLE_OK)
			{
				m_successfullyConnected = true;

				rapidjson_document originAuthInfo;
				originAuthInfo.Parse(readBuffer.c_str());

				if (originAuthInfo.HasParseError())
				{
					spdlog::error(
						"Failed reading origin auth info response: encountered parse error \"{}\"",
						rapidjson::GetParseError_En(originAuthInfo.GetParseError()));
					goto REQUEST_END_CLEANUP;
				}

				if (!originAuthInfo.IsObject() || !originAuthInfo.HasMember("success"))
				{
					spdlog::error("Failed reading origin auth info response: malformed response object {}", readBuffer);
					goto REQUEST_END_CLEANUP;
				}

				if (originAuthInfo["success"].IsTrue() && originAuthInfo.HasMember("token") && originAuthInfo["token"].IsString())
				{
					strncpy(m_ownClientAuthToken, originAuthInfo["token"].GetString(), sizeof(m_ownClientAuthToken));
					m_ownClientAuthToken[sizeof(m_ownClientAuthToken) - 1] = 0;
					spdlog::info("Northstar origin authentication completed successfully!");
				}
				else
					spdlog::error("Northstar origin authentication failed");
			}
			else
			{
				spdlog::error("Failed performing northstar origin auth: error {}", curl_easy_strerror(result));
				m_successfullyConnected = false;
			}

			// we goto this instead of returning so we always hit this
		REQUEST_END_CLEANUP:
			m_bOriginAuthWithMasterServerInProgress = false;
			m_bOriginAuthWithMasterServerDone = true;
			curl_easy_cleanup(curl);
		});

	requestThread.detach();
}
```

This is what is causing it, i dont know cpp LOL so imma have a wild guess.
Ive looked online and they say this is how to make curl not print:

```cpp
			curl_easy_setopt(
				curl,
				CURLOPT_WRITEFUNCTION,
				CURLOPT_URL,
				fmt::format("{}/client/origin_auth?id={}&token={}", Cvar_ns_masterserver_hostname->GetString(), uidStr, tokenStr).c_str());
```
Just a wild guess 😄

**Comment by GeckoEidechse** [comment]
> You are wrong, it does print out the origin token, this is how they changed my pfp and signed into titanfall as me as TTV-iTz_Nao(1) while in karma's server.
> 
> ![Screenshot 2022-05-26 121556](https://user-images.githubusercontent.com/63752443/170477634-171d6033-4f13-4d01-ae55-142514827ff3.png)

Thanks, this is the screenshot I was looking for! :D

So looks like [Bob already made a PR that disables curl logging by default](https://github.com/R2Northstar/NorthstarLauncher/pull/141/), it just wasn't released yet. I'll look into pushing out an update that includes it within the next few days when I get the time ^^

On a sidenote, I suggest updating your Origin password if you haven't already. Not because the auth token gives any form of access to your password but changing the password should reset and log-out all other sessions, cutting off anyone who might have gotten access to your account using that token.

**Comment by GeckoEidechse** [comment]
Pushed the update today already. Player token leak via screenshare should be fixed with [`v1.7.2`](https://github.com/R2Northstar/Northstar/releases/tag/v1.7.2) by disabling curl logs by default.

**Comment by KittenPopo** [comment]
> Not because the auth token gives any form of access to your password but changing the password should reset and log-out all other sessions, cutting off anyone who might have gotten access to your account using that token.

I tried this and my token didn't change lol, they might be permanent

**Comment by GeckoEidechse** [comment]
> I tried this and my token didn't change lol, they might be permanent

They are definitely not permanent based on the master server logs I've seen. The first three characters are. The next 5 characters stay mostly the same, the rest after that seems to change quite frequently.
