### ISSUE TITLE
Make n* generate tier0.dll etc

### ISSUE THREAD

**Issue by TH3-S4LM0N** [R2Northstar/NorthstarLauncher#185]
As a lot of core bin files are generated on first launch of vanilla, it causes a lot of confusion in tickets with ppl just instantly installing n* and not doing first time setup etc. Would it be possible to make Northstar trigger first time setup or generate the bin files somehow just as qol?

**Comment by emma-miler** [comment]
To keep it simple: no

**Comment by KittenPopo** [comment]
This was actually something I was thinking about, it seems like a good idea.

**Comment by GeckoEidechse** [comment]
Yeah, generating it may be hard but we could definitely check if the file exists on launch and if not throw an error message telling players to launch vanilla first.

Ofc, based on tickets I've seen some will just ignore the error and make a ticket anyway but it could help with some at least ^^

**Comment by TH3-S4LM0N** [comment]
so i was cleaning up my open issues etc came back to this
far fetched but theoretically if N* encounters a lack of tier0.dll can it buffer a powershell command to then launch normal Titanfall2.exe after it closes w/ no gui or smthn to genereate the bin stuff?
would probably give proton a mental breakdown but its just a theory rn
