### ISSUE TITLE
Epilogue timings for disabling respawns is earlier than in vanilla Titanfall 2

### ISSUE THREAD

**Issue by Soup-64** [R2Northstar/NorthstarLauncher#20]
**Description:**
On vanilla Titanfall 2, respawning is disabled right after the "epilogue" banner being displayed during gameplay, while on Northstar, respawns get disabled on the "defeat" banner.
**Priority:**
low
**Reasoning:**
To ensure parity in behavior

**Comment by x3Karma** [comment]
This should be in [R2Northstar/NorthstarMods ](https://github.com/R2Northstar/NorthstarMods/) but someone will probably check

**Comment by Soup-64** [comment]
ah my bad, will move the issue now.
