### ISSUE TITLE
Allow log file creation to be disabled

### ISSUE THREAD

**Issue by pg9182** [R2Northstar/NorthstarLauncher#23]

**Comment by LMS007** [comment]
Hey @pg9182 , can you  fill in the feature request details here? Perhaps a why? Thanks!

**Comment by JesperAppelberg** [comment]
Working on an implementation of this now. Will be a launch argument when it is fully implemented. As of right now however more work is needed. Expect it to be working in a few days though

**Comment by Xavierhorwood** [comment]
I think I add what you wanted #44

**Comment by abarichello** [comment]
Implemented in https://github.com/R2Northstar/NorthstarLauncher/commit/c9d66513a85d5325d3d002ca16c82d8302ec0ea2

**Comment by pg9182** [comment]
Thanks!
