### ISSUE TITLE
Mod support for rpaks that use starpaks

### ISSUE THREAD

**Issue by ASpoonPlaysGames** [R2Northstar/NorthstarLauncher#231]
Currently the starpak path found in the rpak is relative to the Titanfall 2 directory (example: `paks\Win64\camo_skin00_col.starpak`).

This can currently be resolved ~~by using the path `R2Northstar\mods\MODNAME\paks\camo_skin00_col.starpak`, or~~ by using the path `paks\Win64\camo_skin00_col.starpak` and putting the starpak in the vanilla folders.

However since the Northstar profile is not guaranteed to be `R2Northstar`, the first option is not good and will break if used in any other profile, and putting mod files outside of the mod folder is also not good, and might cause overriding of vanilla files, which we would rather avoid.

EDIT: `R2Northstar\mods\MODNAME\paks\camo_skin00_col.starpak` doesn't actually work because the paths are relative to the r2 folder not the titanfall 2 folder

**Comment by GeckoEidechse** [comment]
This is still the case, right?

**Comment by ASpoonPlaysGames** [comment]
Shouldn't be as per #279, guess I just forgot to say "closes #231" in there
