### ISSUE TITLE
Logging seems broken when using -northstar to launch

### ISSUE THREAD

**Issue by ASpoonPlaysGames** [R2Northstar/NorthstarLauncher#239]
![image](https://user-images.githubusercontent.com/66967891/185589373-2ee010fd-452f-4cd1-9c3e-ce5a98766d68.png)

**Comment by wolf109909** [comment]
Can confirm this is very reproducible, just purely by luck. (It's much more reproducible from launching with -northstar) Maybe some hook isn't initialized while the function is already called from spdlog?

**Comment by ASpoonPlaysGames** [comment]
Fixed, as per https://github.com/R2Northstar/NorthstarLauncher/pull/320
