### ISSUE TITLE
Secondary weapon keys are inverted with Anti-Titan weapons

### ISSUE THREAD

**Issue by LMS007** [R2Northstar/NorthstarLauncher#24]
When using the key to deploy my anti-titan weapon, it deploys my secondary sidearm and vice versa. Also, when using the switch weapon bind, it toggles between the anti-titan weapon and primary where is should toggle between side arm and primary. I think the logic should adhere to what the standard TF2 game has unless there is a really good reason to change this?

**Comment by abarichello** [comment]
The weapon order is determined by your loadout, you can change it on your end. The default loadout uses 2 for anti-titan and 3 for secondary.

**Comment by LMS007** [comment]
> The weapon order is determined by your loadout, you can change it on your end. The default loadout uses 2 for anti-titan and 3 for secondary.

Thank you! I never change the order in my loadouts so I didn't know!
