### ISSUE TITLE
Duplicate audio overrides cause crashes

### ISSUE THREAD

**Issue by ASpoonPlaysGames** [R2Northstar/NorthstarLauncher#240]
Having two mods that override the same audio event causes a crash, ideally we just follow loadpriority for determining which one gets used

**Comment by GeckoEidechse** [comment]
Was supposed to get fixed by #677 but apparently didn't?

**Comment by Alystrasz** [comment]
> Was supposed to get fixed by #677 but apparently didn't? At least I observed based on some reports. Maybe someone could retest with latest release?

Do you have any conflicting mods or crash logs so we can investigate?
