### ISSUE TITLE
unable to compile release/debug build for x86 (missing curl.h and rapidjson error)

### ISSUE THREAD

**Issue by leifdotwav** [R2Northstar/NorthstarLauncher#25]
hey all,
i'm trying to compile this launcher from source, and i can't seem to get it to build. the first error is that it's somehow not detecting i have curl installed, as it keeps complaining:
`D:\git repos i stole lol\NorthstarLauncher\NorthstarDedicatedTest\masterserver.cpp(6,10): fatal error C1083: Cannot open include file: 'libcurl/include/curl/curl.h': No such file or directory`
it's also complaining a lot about rapidjson, as it keeps saying:
`C:\src\vcpkg\installed\x86-windows\include\rapidjson\document.h(665,59): error C2248: 'rapidjson::GenericMemberIterator<false,Encoding,Allocator>::Iterator': cannot access private typedef declared in class 'rapidjson::GenericMemberIterator<false,Encoding,Allocator>'`
`        with`
`        [`
`            Encoding=rapidjson::UTF8<char>,`
`            Allocator=rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>`
`        ]`
if i could get some help with this, that'd be amazing.

**Comment by GeckoEidechse** [comment]
Since this issue was opened there have been some major changes to the launcher and we now also have [build instructions](https://github.com/R2Northstar/NorthstarLauncher/blob/main/BUILD.md).
Are you able to compile the launcher from source now or is this still and issue?

**Comment by leifdotwav** [comment]
i recloned the entire repo for good measure, built the solution, and it went off with no errors! the only thing i'm a bit concerned about is that it'll only let me compile in x64, not x86. not sure why, but i'm going to try titanfall 2 with this freshly-compiled build!

**Comment by leifdotwav** [comment]
i'm in! however, it's not letting me into multiplayer, just saying that it's connecting to respawn servers. how do i fix this?

**Comment by GeckoEidechse** [comment]
Hmm, maybe try following steps 3 and onward from [the install guide](https://r2northstar.gitbook.io/r2northstar-wiki/installing-northstar/basic-setup).

Also make sure you got the default mods (Client, Custom, CustomServers)  placed in `Titanfall2\R2Northstar\mods\`. These are required to run Northstar. They are just script text files, so no compilation there.

Basically you wanna just follow the the install guide](https://r2northstar.gitbook.io/r2northstar-wiki/installing-northstar/basic-setup) but replace binaries from the zip with the stuff you built yourself.

**Comment by leifdotwav** [comment]
that did the trick! i'm going to close this issue because my issue is solved but i did have one last question: are there any special optimizations i can do if i build northstar myself? i know that gcc has the `march` options for cpu-specific optimizations, so i wanted to know if that sort of thing exists in the compiler visual studio uses.
