### ISSUE TITLE
[Feature Request] Generate Titanfall2-unpacked.exe if missing

### ISSUE THREAD

**Issue by JJRcop** [R2Northstar/NorthstarLauncher#26]
Right now, this launcher requires `Titanfall2-unpacked.exe` to be present with it in the zip file, which means distributing Respawn/EA owned assets.

I think it would be safer for the project if the launcher automatically unpacks/patches `Titanfall2.exe` into `Titanfall2-unpacked.exe` if the latter is missing, then launches it. This way you don't need to distribute the asset with the launcher.

Additionally, it could help speed up packaging new releases, because you don't need to include Titanfall2-unpacked.exe

**Comment by Juesto** [comment]
p0358 PR invalidates this
