### ISSUE TITLE
Game makes system unresponse after staying long in lobby

### ISSUE THREAD

**Issue by MerijnHendriks** [R2Northstar/NorthstarLauncher#27]
## Description

When keeping the game open for an hour while staying in lobby, windows becomes unresponsive with lagging mouse movement.

## How to reproduce

1. Start Titanfall through northstar
2. Enter the multiplayer lobby
3. Stay there for an hour

### Game

- Titanfall 2 (Steam) (on hdd, using DGPU)

### System

- Windows 10 LTSC 2021 (from ssd)
- Intel I7-7700HQ
- 16 GB DDR4 3200Mhz
- NVIDIA GeForce 1050 TI Mobile
- Seagate 256 NVME 
- Seagate 1TB 5400 RPM HDD

## Notes

- Titanfall 2 vanilla performs as expected
- Northstar generates a lot of log information every second.
  Are the hooks being reapplied constantly?

## Attachments

[nslog31-12-2021 17-35-31.txt](https://github.com/R2Northstar/NorthstarLauncher/files/7796706/nslog31-12-2021.17-35-31.txt)

**Comment by p0358** [comment]
I'm wondering if there's any chance you could had a gamepad plugged in and something pushing its analog stick all that time? Gamepad interacts with the game even if it's minimized and not in focus

**Comment by ASpoonPlaysGames** [comment]
Closing as stale, if this is still an issue feel free to reopen
