### ISSUE TITLE
Northstar freezes when launched through Viper (1.9.5)

### ISSUE THREAD

**Issue by ASpoonPlaysGames** [R2Northstar/NorthstarLauncher#271]
[This PR](https://github.com/R2Northstar/NorthstarLauncher/pull/237) that was merged for 1.9.5 (and reverted for 1.9.6) is causing issues in the game when launching through Viper.

From initial investigations, this seems to potentially be a problem with how Viper creates the NorthstarLauncher process?

**Comment by GeckoEidechse** [comment]
I'd suggest making separate PRs for the log colouring and removal of `freopen` each to see which of the two is actually causing the issue ^^

**Comment by Alystrasz** [comment]
Should be fixed with newer Viper releases.

**Comment by GeckoEidechse** [comment]
Closing as completed.
