### ISSUE TITLE
Right clicking the console can crash the game

### ISSUE THREAD

**Issue by ASpoonPlaysGames** [R2Northstar/NorthstarLauncher#313]
Got this report from someone on discord, issue was on 1.9.7 but persisted into 1.10.2, they were on Windows 10.
I am unable to reproduce this issue personally.

Relevant logs:
1.10.2: [nslog2022-10-29_02-39-24.txt](https://github.com/R2Northstar/NorthstarLauncher/files/9892541/nslog2022-10-29_02-39-24.txt)
1.9.7: [nslog2022-10-29_02-31-03.txt](https://github.com/R2Northstar/NorthstarLauncher/files/9892542/nslog2022-10-29_02-31-03.1.txt)

**Comment by GeckoEidechse** [comment]
Never had this issue on my end either.

**Comment by ASpoonPlaysGames** [comment]
I'm going to close this as stale, since nobody else has reported this issue, nor been able to reproduce it in 10 months
