### ISSUE TITLE
Server Failes to Fully Initialize - Attempted to read from: 0x00000030

### ISSUE THREAD

**Issue by IceOfWraith** [R2Northstar/NorthstarLauncher#33]
I'm attempting to run the server under AMP by CubeCoders as a generic module. This runs under the Network Service user. I'm able to start the server fine using the same files outside of AMP, but get the attached error when attempting inside. I am more than willing/capable to diagnose the AMP side, but would appreciate any guidance on the NorthStar side. Can you please shed some light on where I might look for the cause?

[nslog03-01-2022 05-14-44.txt](https://github.com/R2Northstar/NorthstarLauncher/files/7801610/nslog03-01-2022.05-14-44.txt)

**Comment by JesperAppelberg** [comment]
I don't have too much experience debugging northstar, however. From what I can tell the issue might be related to the disallowed weapons script. It might also be related to another mod running on the server. Are you running anything other than a stock northstar server? Any custom scripts etc.? Might be the cause of your issue

**Comment by IceOfWraith** [comment]
Thanks for the reply! This error usually comes after the D3d device hook, so I thought it might be related. This log stuck out because it didn't. So I think the timing in the logs is just when it happens to load this part. I have no other mods included. And the server loads outside of AMP using the same files and configs/startup command.

**Comment by JesperAppelberg** [comment]
Stupid question but I am not very familiar with AMP. Do you have to install prerequsites such as DX11 and others manually?
Looking further into the log, the error seems to be related to the materialsystem_dx11.dll. 
I have not had time to look into the code itself for this specific issue, but maybe it is that dx11 is not installed on AMP. Or incorrectly installed causing it to crash.

**Comment by Xavierhorwood** [comment]
> Thanks for the reply! This error usually comes after the D3d device hook, so I thought it might be related. This log stuck out because it didn't. So I think the timing in the logs is just when it happens to load this part. I have no other mods included. And the server loads outside of AMP using the same files and configs/startup command.

try and use "-softwared3d11" as a launch argument and see if it works

**Comment by Xavierhorwood** [comment]
try verify the game files

**Comment by IceOfWraith** [comment]
Yes, it does have a graphics card and drivers installed. An RTX 3060. This seems to be directly related to being ran under NetworkService even though the D3D device is setup as WARP.

**Comment by ASpoonPlaysGames** [comment]
Closing as stale, if this is still an issue on recent builds feel free to reopen
