### ISSUE TITLE
Server not sending updated playercounts rarely

### ISSUE THREAD

**Issue by james-amarth** [R2Northstar/NorthstarLauncher#356]
The bug that was resolved in #305 is back, though not nearly as bad as before as it very rarely shows up. Playercounts are rarely not being updated, and I've only seen it happen twice over now, once on my own server and once on one of Maus' Attrition servers. Both occurrences had a full server reporting 11/12 players on.

https://user-images.githubusercontent.com/116909003/205193910-77bfdba8-dca3-4570-818b-b1f321105a76.mp4

**Comment by emma-miler** [comment]
Should be fixed in latest
