### ISSUE TITLE
The game becomes unresponsive when tabbing out

### ISSUE THREAD

**Issue by platnummunkey** [R2Northstar/NorthstarLauncher#4]
The game becomes unresponsive when tabbing out on fullscreen.

**Comment by MiloAkerman** [comment]
Unresponsive how?

**Comment by Haplo164** [comment]
I tabbed out during a map change and got an infinite loading screen.

**Comment by ASpoonPlaysGames** [comment]
Closing as stale, there are quite a few reasons why this could happen (things like the server dying)
