### ISSUE TITLE
Crashes not flushing log to disk properly

### ISSUE THREAD

**Issue by GeckoEidechse** [R2Northstar/NorthstarLauncher#401]
I started noticing crashes where in the crash log there's no stack trace, making it near impossible to find the cause.

Confirmed happening in Frontier War and Attrition.

No way to reproduce consistently yet.

Interestingly when observed the stack trace does seem to get printed properly to the console window.

**Comment by DoomslayerMark** [comment]
my northstar launcher is crash ever time

**Comment by GeckoEidechse** [comment]
Potential way of reproduce

```
sv_cheats 1; script thread function(){throw ""}()
```

**Comment by GeckoEidechse** [comment]
Should be fixed with #413
