### ISSUE TITLE
Plugin:player uid not available

### ISSUE THREAD

**Issue by R2-Simmo** [R2Northstar/NorthstarLauncher#417]
Never update this value

**Comment by GeckoEidechse** [comment]
Could you maybe elaborate a bit what you mean with this? ^^

**Comment by R2-Simmo** [comment]
when i try to got player uid in plugins,there always return a same integer "123",so it may not works

**Comment by catornot** [comment]
plugins v2 or v1?

**Comment by R2-Simmo** [comment]
> plugins v2 or v1?

may v1,i copied the plugin_abi.h from sources

**Comment by catornot** [comment]
v1 simply doesn't set some of the values.

**Comment by R2-Simmo** [comment]
> v1 simply doesn't set some of the values.
> 

that means i cant got uid by plugin v1 right?
thanks very much.
