### ISSUE TITLE
Add startup arg that disabled engine error prompts for auto-restart scripts

### ISSUE THREAD

**Issue by wolf109909** [R2Northstar/NorthstarLauncher#42]
Disable the engine error prompts to make the game crash right away when encountering these issues. Maybe redirect the messages from that error prompt to somewhere else like in a file?
eg:
![unknown](https://user-images.githubusercontent.com/84360921/148632385-be074376-7175-4101-b3fa-b90193b18467.png)

**Comment by barnabwhy** [comment]
turns out respawn already did this one for us, you can use `-nomessagebox` in startup args to disable engine error prompts
