### ISSUE TITLE
Access violation when loading custom maps

### ISSUE THREAD

**Issue by F1F7Y** [R2Northstar/NorthstarLauncher#423]
When loading a custom map from the lobby half the time I crash [here](https://github.com/R2Northstar/NorthstarLauncher/blob/main/NorthstarDLL/engine/hoststate.cpp#L121-L134).

## Steps to reproduce
1. Launch latest northstar ( This issue was made when [32165af](https://github.com/R2Northstar/NorthstarLauncher/tree/32165afe41c4cf4d3b261ee7a9c69c369253cc13) is latest )
2. Load into multiplayer
3. Run: `map mp_frostbite`

## Files
[nslog2023-02-24 21-46-51.txt](https://github.com/R2Northstar/NorthstarLauncher/files/10829269/nslog2023-02-24.21-46-51.txt)
[Fifty.mp_frostbite.zip](https://github.com/R2Northstar/NorthstarLauncher/files/10829247/Fifty.mp_frostbite.zip)

**Comment by catornot** [comment]
Huh I thought it was smth related to my maps.
I guess not.

**Comment by Alystrasz** [comment]
Maybe the issue was linked to the map version; using latest map version ([from Thunderstore](https://thunderstore.io/c/northstar/p/Fifty/Frostbite/)), I could load the map from lobby with no issue.
