### ISSUE TITLE
DLL deemed trojan malware

### ISSUE THREAD

**Issue by goatsd** [R2Northstar/NorthstarLauncher#43]
[VirusTotal](https://www.virustotal.com/gui/file/6b579459d75d553da29bee669893d234c88cc474c76dff1d95610b661effca6a/detection) deems the .dll file malware.

obv. a false positive, as previously with NorthstarLauncher.exe

i've contacted MaxSecure about whitelisting the file, so i'll wait for an email response.

**Comment by abarichello** [comment]
Will probably never get whitelisted due to the usage of windows api to overwrite stuff.
