### ISSUE TITLE
Safe I/O file name encoding

### ISSUE THREAD

**Issue by EladNLG** [R2Northstar/NorthstarLauncher#440]
I don't know where to put this, but file name encoding seems to fail with non-ASCII characters, as you can see in this screenshot: 

![image](https://user-images.githubusercontent.com/11993538/223225530-d1a5ab23-847f-44c1-9436-66998f4088d6.png)
Related squirrel code:
```javascript
NSSaveFile( "héllo.json", "héy" )
```

Note that loading the file (*i.e. `NSLoadFile( "héllo.json", [...])`) works correctly with non-ASCII characters.

_Originally posted by @Alystrasz in https://github.com/R2Northstar/NorthstarLauncher/pull/404#discussion_r1127012778_

(This doesn't affect decoding of the file, which still works fine. The file name is returned correctly, and this has been deemed not important enough to fix before merge.)

For now, Safe I/O paths are restricted to ASCII until this is fixed, for compatibility reasons.

**Comment by pg9182** [comment]
We honestly should restrict it just to ASCII, if only for compatibility more than anything else. Not all filesystems support non-ASCII filenames, and all platforms handle them differently. I haven't looked into how Wine does it specifically.

Some interesting reads:
- https://learn.microsoft.com/en-us/windows/win32/intl/character-sets-used-in-file-names
- https://lwn.net/Articles/744176/
- https://news.ycombinator.com/item?id=4226916

**Comment by Alystrasz** [comment]
As described in [`modsavefiles.cpp#L207`](https://github.com/R2Northstar/NorthstarLauncher/blob/main/primedev/mods/modsavefiles.cpp#L207):

> Paths are restricted to ASCII because encoding is fucked and we decided we won't bother.
