### ISSUE TITLE
Cannot run Northstar without mods in `v1.13.0`

### ISSUE THREAD

**Issue by GeckoEidechse** [R2Northstar/NorthstarLauncher#456]
Running Northstar without any mods (to e.g. play on vanilla servers) gives

![image](https://user-images.githubusercontent.com/40122905/233814634-e3423173-6edc-4055-a2df-c8c8bbb5ddf3.png)

**Comment by GeckoEidechse** [comment]
Apparently caused by plugins according to @catornot

**Comment by catornot** [comment]
the `InitScript` part of plugins v2 

who actually plays vanilla with northstar anyway.

**Comment by catornot** [comment]
oh I found the issue lol

the `CSquirrelVM_init` hook never checks if mods are enabled -> [squirrel.cpp#L416](https://github.com/R2Northstar/NorthstarLauncher/blob/7c2b56b1e978a23c55bb1d587a6633a7de81185c/NorthstarDLL/squirrel/squirrel.cpp#L416)

**Comment by ASpoonPlaysGames** [comment]
> who actually plays vanilla with northstar anyway.

quite a few people actually
