### ISSUE TITLE
what can i do in this situation ? 

### ISSUE THREAD

**Issue by skychinezu** [R2Northstar/NorthstarLauncher#464]
![image](https://github.com/R2Northstar/NorthstarLauncher/assets/134332026/c6ef80d3-1bc3-4af0-ad8f-1454c95eb2b7)

When i run the game it start normal and i see this when i try to join multiplayer

**Comment by catornot** [comment]
you also need to update northstar mods or to simply enable them.

**Comment by skychinezu** [comment]
i don t have any mods it s my frist time downloading this

**Comment by ASpoonPlaysGames** [comment]
Closing as fixed. while the actual log spam is an issue, it is being tracked in another issue already (and should be fixed by plugins v3)
