### ISSUE TITLE
Encountered CLIENT script compilation

### ISSUE THREAD

**Issue by chislerr** [R2Northstar/NorthstarLauncher#466]
![Снимок экрана 2023-06-02 172236](https://github.com/R2Northstar/NorthstarLauncher/assets/135347612/33aa0a04-f264-4131-a7d5-b6a277a65765)
![Снимок экрана 2023-06-02 172259](https://github.com/R2Northstar/NorthstarLauncher/assets/135347612/6094f8cc-e528-4f7c-b6ec-fccacc4df2d2)

how can i fix this?

**Comment by uniboi** [comment]
your screenshots don't show the compile error

**Comment by chislerr** [comment]
> your screenshots don't show the compile error

but this is all i've got, maybe error log will help
[nslog2023-06-02 17-21-32.txt](https://github.com/R2Northstar/NorthstarLauncher/files/11636526/nslog2023-06-02.17-21-32.txt)

**Comment by uniboi** [comment]
update cod scoring

**Comment by chislerr** [comment]
> update cod scoring when the issue is fixed

thx a lot it helped

**Comment by lidrerry** [comment]
?I met the same problem,but how to solve?

**Comment by GeckoEidechse** [comment]
most likely conflicting or outdated mods. Disable all mods except the `Northstar.*` ones and try again. If that doesn't fix it, make a post [here](https://github.com/R2Northstar/Northstar/discussions/categories/tech-support) or open a support ticket on the Northstar Discord.
