### ISSUE TITLE
Forgot to update version resource

### ISSUE THREAD

**Issue by GeckoEidechse** [R2Northstar/NorthstarLauncher#47]
We forgot to update the [version resource in the launcher](https://github.com/R2Northstar/NorthstarLauncher/blob/main/LauncherInjector/resources.rc#L64) on `v1.4.0` release.
(Lines 64, 65, 82, 87)

We probably wanna add that to some release checklist, maybe even do a safety check in CI to make sure values on those lines and release tag match up.

**Comment by iCrazyBlaze** [comment]
Could this process be automated across the whole project with the build number everywhere being updated from one text file when building?

**Comment by abarichello** [comment]
I'll probably update resource strings to 'MASTER_BRANCH' and have them replaced on the build pipeline

**Comment by abarichello** [comment]
The resource version is set to DEV and 0,0,0,0 on master branch: https://github.com/R2Northstar/NorthstarLauncher/commit/ce369d39889304b5712e9628c7ae084c27a1cce2
I added a github actions step to replace those with the tag that's being built: https://github.com/R2Northstar/Northstar/pull/146/commits/922a4817767c9089a2a8cf9e7570020897b0e8e9

**Comment by GeckoEidechse** [comment]
Do we maybe also apply a similar action to the NorthstarMods?
(assuming we change the version to mirror that of release)

**Comment by abarichello** [comment]
> Do we maybe also apply a similar action to the NorthstarMods? (assuming we change the version to mirror that of release)

I'll try to do that next
