### ISSUE TITLE
undefined reference `__sq_getentity`

### ISSUE THREAD

**Issue by Jan200101** [R2Northstar/NorthstarLauncher#475]
https://github.com/R2Northstar/NorthstarLauncher/blob/89996405ee6341252836d606d5de02fff83ec3ab/NorthstarDLL/squirrel/squirrel.h#L281-L284

No definition for `__sq_getentity` appears to exist on master.

`__sq_getentity` was introduced by #171
and removed in https://github.com/R2Northstar/NorthstarLauncher/commit/0c729c609cd052f4e720ce885c1d5322b63c9edd

I am unsure if this `__sq_getentity` is the proper passthrough for `getthisentity`, shouldn't it be `__sq_getthisentity`?

**Comment by GeckoEidechse** [comment]
Assigning @BobTheBob9 cause git blame says this was changed in #171 (big refactor). Probably just got moved around but too lazy to check ^^
