### ISSUE TITLE
2 copies of MinHook?

### ISSUE THREAD

**Issue by Jan200101** [R2Northstar/NorthstarLauncher#484]
there are currently 2 copies of MinHook vendored in NorthstarLauncher:
- [include/MinHook.x64.lib](https://github.com/R2Northstar/NorthstarLauncher/blob/main/include/MinHook.x64.lib)
- [loader_wsock32_proxy/include/MinHook.x64.lib](https://github.com/R2Northstar/NorthstarLauncher/blob/main/loader_wsock32_proxy/include/MinHook.x64.lib)

Was this an oversight or are these two different versions?

**Comment by F1F7Y** [comment]
They very much look identical.

With the move to cmake there were talks of compiling all libraries ourselves, but noone has looked into it as far as im aware

**Comment by Jan200101** [comment]
Shouldn't be a problem with libcurl and minhook, since both provide cmake solutions (see https://cmake.org/cmake/help/latest/module/ExternalProject.html)
