### ISSUE TITLE
Preventing "Lost Connection to Origin" when you have no internet connection

### ISSUE THREAD

**Issue by jamesla** [R2Northstar/NorthstarLauncher#506]
I'm hosting a lan in a few weeks which won't have an internet connection and we are trying to make titanfall2 feature as one of the games.

I have the dedicated server running in insecure mode which allows clients to connect without authenticating with the master server and is working fine by opening the client and using `/connect x.x.x.x`.

Now when I disconnect the internet connection altogether it almost connects but then throws the error:
```
Lost connection to Origin
```

And I'm assuming tht's because origin is not logged in - given that there is no internet connection.

Is there any sort of mod/command in order to /connect to a dedicated lan server and not require the client to actively be logged into Origin?

**Comment by F1F7Y** [comment]
There is no cvar or mod to do this.

Going by bobs comments [here](https://github.com/R2Northstar/NorthstarLauncher/blob/main/NorthstarDLL/dedicated/dedicated.cpp#L264-L266) it sounds like even if we allow clients to start without origin the game would throw a fit and probably engine error or crash.

**Comment by GeckoEidechse** [comment]
> Is there any sort of mod/command in order to /connect to a dedicated lan server and not require the client to actively be logged into Origin?

Doubt we can make that work without also enabling pirated versions of the game. Given that the game is still available for purchase (and we don't want to get sued by EA) we have a strong stance against pirating Titanfall2.

**Comment by jamesla** [comment]
Ok fair point - we'll try track down a 3g router or something thanks
