### ISSUE TITLE
Remove `run_northstar.txt` functionality 

### ISSUE THREAD

**Issue by Jan200101** [R2Northstar/NorthstarLauncher#508]
Inspired by #507

## Why
the behavior of `run_northstar.txt` is inconcistent with launch flags depending on the method used:
- wsock32 proxy does not support `vanilla` and thus `run_northstar.txt` with `1` cannot be passed by
- NorthstarLauncher does not support `-northstar` and thus `run_northstar.txt` with `0` cannot be passed by

## How
1. Some people may still have the file from outdated linux installs (or other)
   it would be best to do some sort of warning before removing functionality.
2. The only mod manager that made use of it was FlightCore, and that was recently changed to use launch flags directly.

**Comment by GeckoEidechse** [comment]
We might wanna do a scream test for this first where basically we just gate the logic behind an `if(false){...}`. If no one complains in a month or two we drop it.

The main use of it rn is Steam setup with non-NorthstarProton/latest Proton-GE. For example, I'm pretty sure I still use it on my SteamDeck cause I haven't updated Proton install yet.

Similarly we'll need to update docs accordingly. So like I'd propose feature flag for scream test + updated docs, wait a while, remove.

**Comment by Jan200101** [comment]
> The main use of it rn is Steam setup with non-NorthstarProton/latest Proton-GE.

Yeah, its a bummer that its still stuck in PR hell.
I've gone ahead and made a PR that removes it via preprocessors, I'll also go ahead and see if I can find anyone to look at the Proton PR

**Comment by Jan200101** [comment]
> The main use of it rn is Steam setup with non-NorthstarProton/latest Proton-GE. For example, I'm pretty sure I still use it on my SteamDeck cause I haven't updated Proton install yet.

soon no more, the PR has been merged into Proton and it will be included in the next release.

**Comment by GeckoEidechse** [comment]
> soon no more, the PR has been merged into Proton and it will be included in the next release.

Wait upstream Proton to not overwrite the DLL or which one? ^^"
Link? :point_right::point_left:

**Comment by Jan200101** [comment]
the flag thing.
a wine dll override can be added via the launch options
