### ISSUE TITLE
Add support for loading plugins from `packages` directory

### ISSUE THREAD

**Issue by GeckoEidechse** [R2Northstar/NorthstarLauncher#509]
#503 add support for loading unpacked Thunderstore mods directly from `packages`. However it doesn't support loading plugins yet.

As plugins can be uploaded to Thunderstore, this functionality should be added to NorthstarLauncher.

**EDIT:** An example of a plugin on Thunderstore: https://northstar.thunderstore.io/package/cat_or_not/kyurid/

**Comment by Jan200101** [comment]
Is there any example for a thunderstore plugin?

**Comment by GeckoEidechse** [comment]
https://northstar.thunderstore.io/package/cat_or_not/kyurid/
