### ISSUE TITLE
dedicated: Export prometheus metrics

### ISSUE THREAD

**Issue by pg9182** [R2Northstar/NorthstarLauncher#51]
The dedicated server should export metrics. I will probably work on an initial version of this in my docker image, but I may end up just directly implementing it in the launcher itself.

Some ideas for useful metrics:

- counter `northstar_instance_ticks_total`
- counter `northstar_instance_uptime_seconds`
- gauge `northstar_instance_info{arguments, game_port, auth_port}` (more?) = 1 (maybe?)
- gauge `northstar_match_player_count`
- gauge `northstar_match_player_limit`
- gauge `northstar_match_info{playlist_name, map_name}` = 1
- gauge `northstar_match_duration_seconds`
- histogram `northstar_network_client_latency_milliseconds{uid}` (maybe?)
- counter `northstar_network_receive_bytes`
- counter `northstar_network_transmit_bytes`
- counter `northstar_network_receive_packets`
- counter `northstar_network_transmit_packets`
- guage `northstar_cpu_seconds_total`
- guage `northstar_memory_physical_bytes`
- guage `northstar_memory_virtual_bytes`

**Comment by p0358** [comment]
I should drop 2 links I saved when doing my research on this area of stuff before I gave up for that time being in hopes they'll be helpful for inspiration:

https://www.reddit.com/r/gamedev/comments/dwolyk/monitoring_serverside_ecs_application_with/

https://skylar.tech/tracking-game-server-statistics-using-node-red-influxdb-and-grafana/

**Comment by pg9182** [comment]
Somewhat related, but relevant, so I'll note it here: I threw together a prometheus exporter for the master server and created a few dashboards (temporary links: [[1]](http://45.79.182.79:8081/d/R1hKFea7k/northstar-tf-server-overview?orgId=1&theme=light&kiosk=tv&refresh=30s) [[2]](http://45.79.182.79:8081/d/IO1luCanz/northstar-tf?orgId=1&theme=light&kiosk=tv&refresh=30s)).

| ![45 79 182 79_8081_d_IO1luCanz_northstar-tf_orgId=1 from=now-2d to=now](https://user-images.githubusercontent.com/96569817/154334017-b329d9f4-e601-4fd2-8aad-677a32760412.png) | ![image](https://user-images.githubusercontent.com/96569817/154333959-aadced3c-bb8d-45ac-882e-c2df75179160.png) |
| --- | --- |

**Comment by ASpoonPlaysGames** [comment]
@pg9182 is this completed/stale? (can it be closed?)

**Comment by pg9182** [comment]
Stale.
