### ISSUE TITLE
profiles with spaces in the name

### ISSUE THREAD

**Issue by Klemmbaustein** [R2Northstar/NorthstarLauncher#532]
There doesn't seem to be a way to load a profile if a space is the path to the profile.
For example: 
`./NorthstarLauncher.exe -profile="Cool Profile"` tries to launch a profile called `Cool`.

**Comment by ASpoonPlaysGames** [comment]
https://github.com/R2Northstar/NorthstarLauncher/blob/07e76e3a8e2738dbb7a1d5a6aeaa908a838f5a02/NorthstarLauncher/main.cpp#L278 is the code that handles this, although seemingly doesn't work according to this?

**Comment by Klemmbaustein** [comment]
for some reason this works, but not when launching through powershell

**Comment by F1F7Y** [comment]
powershell:
![image](https://github.com/R2Northstar/NorthstarLauncher/assets/64418963/d9b7e880-9d15-4934-8171-52118778fecf)
![image](https://github.com/R2Northstar/NorthstarLauncher/assets/64418963/fdd9bfa8-033c-4464-8351-c912497cc7d0)

cmd:
![image](https://github.com/R2Northstar/NorthstarLauncher/assets/64418963/cbb1bad0-04c3-4f5d-8f3f-e1b108aba26c)


black background were printed by ns at startup

seems like powershell quotes each argument and removes all `"`

**Comment by F1F7Y** [comment]
Solution: use winapi

**Comment by ASpoonPlaysGames** [comment]
Perhaps escaping the quotes could stop powershell from doing what it's doing
