### ISSUE TITLE
Crashes on respawn

### ISSUE THREAD

**Issue by drazzell1132** [R2Northstar/NorthstarLauncher#54]
I am not very gifted in the field of coding and whatnot but I'm having a rather consistent issue. Simply skipping the killcam and respawning results in a crash to desktop. Crash log attached
[nslog2022-01-23 17-27-19.txt](https://github.com/R2Northstar/NorthstarLauncher/files/7922170/nslog2022-01-23.17-27-19.txt)
.

**Comment by ASpoonPlaysGames** [comment]
Can you remember what you died to when you crashed in that log?

**Comment by ASpoonPlaysGames** [comment]
Also next time it happens, I would appreciate it if you could record the moments leading up to the crash

**Comment by drazzell1132** [comment]
I'll see what I can do. I don't recall what I died to, but it isn't a crash as soon as I'm killed as much as when I respawn.

**Comment by drazzell1132** [comment]
The crash happened again after I was killed by an EPG. Sadly i did not get a recording.

**Comment by GeckoEidechse** [comment]
There have been many releases since. I'm closing this as stale. If you encounter this issue again, please open a new GitHub issue and link to this one.
