### ISSUE TITLE
Rework `-vanilla` launch option to be a vanilla compatibility mode

### ISSUE THREAD

**Issue by ASpoonPlaysGames** [R2Northstar/NorthstarLauncher#588]
Currently, `-vanilla` is a pretty useless launch option that nobody uses. It basically is used by `NorthstarLauncher.exe` to launch the vanilla game without loading `Northstar.dll`

`-norestrictservercommands` is the current way of being "vanilla compatible" but is missing some things, so this would become a replacement for `-norestrictservercommands` being used for this

**Comment by p0358** [comment]
The reason for `-vanilla` was to cover a case where Origin/EA App would sometimes refuse to fire up the game for no reason, so you could use this to work around it and still play the original game.

Not sure for how many people it still happens and how many people use this option at least sometimes, but I'd be hesitant to just remove it with no replacement...  Maybe do with `-vanilla` as you're saying, but make some new option for its current behavior? `-vanillaOnly`, `-pureVanilla`?

**Comment by ASpoonPlaysGames** [comment]
Sure, that works for me
