### ISSUE TITLE
Incorrect plugin name used in logs

### ISSUE THREAD

**Issue by okvdai** [R2Northstar/NorthstarLauncher#597]
My plugin's (repository currently private) logs have an incorrect display name (the DiscordRPC one) attached to them, as shown below:
![image](https://github.com/R2Northstar/NorthstarLauncher/assets/108829133/911a462f-9dee-41eb-9584-859b11b172e3)

Removing `DiscordRPC.dll` from the `...\R2Northstar\plugins` folder resolves this issue:
![image](https://github.com/R2Northstar/NorthstarLauncher/assets/108829133/0ddd9938-0840-4109-ae9a-5b7d2d81f942)

I've tested this with [kyurid](https://github.com/catornot/kyurid) too, and I have the same issue with it as well:
![image](https://github.com/R2Northstar/NorthstarLauncher/assets/108829133/47ecf747-68c0-46cb-b8a0-21826705a12a)

DiscordRPC and kyurid seem to work together fine though, but the display name of my plugin is rewritten.
This issue can be recreated by making a plugin using [my fork of F1F7Y's R2PluginTemplate](https://github.com/okvdai/R2PluginTemplate) modified so that it could be used for v3 plugins, and putting the compiled dll file in the `plugins` folder alongside DiscordRPC / kyurid.

Important: for some reason, this issue started only when I changed the plugin's display name from the template default of `CPLUGTEST`.

**Comment by okvdai** [comment]
Upon further testing I've come to the conclusion that if I give my plugin a display name that comes before `DPRESENCE` in the alphabet, it works like it should. Example below:
![image](https://github.com/R2Northstar/NorthstarLauncher/assets/108829133/1970eaec-f455-41b1-acc0-08070c1fcd9f)
Example of non-working (display name set to `VISORPLUG`):
![image](https://github.com/R2Northstar/NorthstarLauncher/assets/108829133/3dd5c7a6-7aed-4aef-a0d0-3382f15b3a16)

**Comment by catornot** [comment]
looks like you don't the provided plugin handle when calling the log function.

**Comment by okvdai** [comment]
whoops, that's a skill issue on my part, my bad...
