### ISSUE TITLE
Allow mods to hook chat messages

### ISSUE THREAD

**Issue by GeckoEidechse** [R2Northstar/NorthstarLauncher#63]
# Goal

By adding a way for mods to read chat messages mods can then be used to perform actions based on a message sent in chat.

## Background

For example currently there are already mods that allow you to vote skip maps like [Takyon.PlayerVote](https://github.com/ScureX/Takyon.PlayerVote) by issuing a command like `!skip` via the console.

The issue is that the console is not the most accessible place to issue such commands.

- Players new to Northstar might not know how to open the console.
- Players on keyboards other than ANSI-US or ISO-UK (like ISO-DE) might not even be able to open the console in the first place as the default key assigned to opening the console does not exist there. Instead those players first need to remap the console key by opening the keybinds settings file or adding a launch argument to Northstar.

## Additional

Depending on the command it might not be wise to broadcast the message back to other players. So allowing a server mod to prevent forwarding such a message might be another thing worth investigating.

**Comment by emma-miler** [comment]
Started work on this, should get it working before the end of this weekend.

**Comment by emma-miler** [comment]
This has been done. Can close now ^^
