### ISSUE TITLE
Northstar Launcher not logging in the Console window.

### ISSUE THREAD

**Issue by EM4Volts** [R2Northstar/NorthstarLauncher#752]
I use 1.26.3.0 didnt test on other versions but the Out of game console window randomly only prints

`[*] Loading tier0.dll
[*] Loading Northstar
[*] Profile was not found in command line arguments. Using default: R2Northstar
[*] Using: D:\SteamLibrary\steamapps\common\Titanfall2\Northstar.dll`

and nothing else, game sitll launches, ingame console works fine.

**Comment by ASpoonPlaysGames** [comment]
Possibly related to #741?

**Comment by RoyalBlue1** [comment]
> Possibly related to #741?

it seems so I could get this issue within 7 tries with that change and with it reverted I tested about 40 times without getting the issue

**Comment by GeckoEidechse** [comment]
so weird though that a) it's random and b) it's caused by that change...

**Comment by ASpoonPlaysGames** [comment]
This issue (prior to my change that then got partially reworked in that PR) used to be a thing, same as now.

It's likely a race condition of sorts, prevented by running `AllocConsole` which that PR stops doing all the time

**Comment by GeckoEidechse** [comment]
So should we just revert #741 then?
