### ISSUE TITLE
Update Northstar icon to higher resolution

### ISSUE THREAD

**Issue by GeckoEidechse** [R2Northstar/NorthstarLauncher#78]
The current icon is only 32x32 pixels large

![current icon](https://raw.githubusercontent.com/R2Northstar/NorthstarLauncher/main/LauncherInjector/ns_icon.ico)

I don't know the limitations on icon size in win32 but we can definitely go higher than that. I'd suggest using a downscaled version from @xamionex [updated version](https://github.com/xamionex/NorthstarLogo/blob/master/Images/NorthstarLOGO.png).

**Comment by barnabwhy** [comment]
I could try this, iirc up to 128x128 could be ised

**Comment by emma-miler** [comment]
#97

**Comment by barnabwhy** [comment]
Should be closed
