### ISSUE TITLE
Broken language hooks

### ISSUE THREAD

**Issue by GeckoEidechse** [R2Northstar/NorthstarLauncher#797]
As discovered in https://github.com/R2Northstar/NorthstarLauncher/pull/787#issuecomment-231748903 the language hooks utilising `-language` appear to not work at all.

This was the case even before the PR the comment was made on. It's unclear for how long they have been broken or what change caused them to break (or if they even worked in the first place lol).

**Comment by Gazyi** [comment]
In [#787 (comment)](https://github.com/R2Northstar/NorthstarLauncher/pull/787#issuecomment-2317489037) both commands have typos.
Origin version, added `-language polish` in ns_startup_args. I don't see any problems.
`[2024-09-08] [09:52:46] [NORTHSTAR] [info] User forcing the language (-language) to: polish`
![snapshot0000](https://github.com/user-attachments/assets/4916fd8f-8784-4b18-9378-7e13b02da7e2)

**Comment by GeckoEidechse** [comment]
> In [#787 (comment)](https://github.com/R2Northstar/NorthstarLauncher/pull/787#issuecomment-2317489037) both commands have typos.
> Origin version, added `-language polish` in ns_startup_args. I don't see any problems.

Omfg, how did neither me nor anyone else looking at the PR notice this x_x

Anyway, thanks for testing <3

I'm closing this issue as skill issue on my end xD
