### ISSUE TITLE
Northstar crashes if R2Northstar/logs does not exist

### ISSUE THREAD

**Issue by pg9182** [R2Northstar/NorthstarLauncher#82]
As of 1a7b41cc722c05eb97006d29e124c17559c45324 (unreleased).

I haven't checked it yet, but my hunch is that it's a regression related to this https://github.com/R2Northstar/NorthstarLauncher/pull/73/files#diff-fc1e49c087e0aa0e7e432a10288ddbd465d6ed30ccb5946c2deea666386e974aR52.

**Comment by GeckoEidechse** [comment]
@Legonzaur

**Comment by Legonzaur** [comment]
Best thing to do would be to revert #76 and #73 and merge log rotation when it's done

**Comment by GeckoEidechse** [comment]
As the relevant commit was reverted already I think this issue can be closed :P
