### ISSUE TITLE
game crash on 1.5.1

### ISSUE THREAD

**Issue by L1ghtman2k** [R2Northstar/NorthstarLauncher#91]
Cause: Not sure, but I was in an LTS match, and as soon as the next game started it crashed the client

[nslog2022-02-21 00-38-14.zip](https://github.com/R2Northstar/NorthstarLauncher/files/8106539/nslog2022-02-21.00-38-14.zip)

**Comment by GeckoEidechse** [comment]
Kinda hard to reproduce this bug without knowing what might have caused it. That and considering that `v1.5.1` has since been obsoleted I'm just gonna close the issue for being stale. If it happens again on a current version please re-open or make a new issue referencing this one.
